ColorVRWebSite/ColorVRWebSite/ViewModels/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ColorVRWebSite.Data.Models;
namespace ColorVRWebSite.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<PlayGrounds> preferedPlayGrounds { get; set; }
    }
}

ColorVRWebSite/ColorVRWebSite/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ColorVRWebSite.ViewModels
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name ="User Name")]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string ReturnUrl { get; set; }
    }
}

ColorVRWebSite/ColorVRWebSite/ViewModels/PlayGroundsListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ColorVRWebSite.Data.Models;

namespace ColorVRWebSite.ViewModels
{
    public class PlayGroundsListViewModel
    {
        public IEnumerable<PlayGrounds> playGrounds { get; set; }
        public string currentCategory { get; set; }   
    }
}

ColorVRWebSite/ColorVRWebSite/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ColorVRWebSite.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ColorVRWebSite.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;

        public AccountController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        public IActionResult Login(string returnUrl)
        {
            return View(new LoginViewModel
            {
                ReturnUrl = returnUrl
            });
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel loginViewModel)
        {
            if (!ModelState.IsValid)
                return View(loginViewModel);

            var user = await _userManager.FindByNameAsync(loginViewModel.UserName);

            if (user != null)
            {
                var result = await _signInManager.PasswordSignInAsync(user, loginViewModel.Password, false, false);
                if (result.Succeeded)
                {
                    if (string.IsNullOrEmpty(loginViewModel.ReturnUrl))
                        return RedirectToAction("Index", "Home");

                    return Redirect(loginViewModel.ReturnUrl);
                }
            }
            ModelState.AddModelError("", "Username/password not found");
            return View(loginViewModel);

        }

        public IActionResult Register() => View();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(LoginViewModel loginViewModel)
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser() { UserName = loginViewModel.UserName };
                var result = await _userManager.CreateAsync(user, loginViewModel.Password);

                if (result.Succeeded)
                {
                    return RedirectToAction("LoggedIn", "Account");
                }
            }
            return View(loginViewModel);
        }

        public ViewResult LoggedIn() => View();


        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

ColorVRWebSite/ColorVRWebSite/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ColorVRWebSite.Controllers
{
    public class ContactController : Controller
    {
        public ViewResult Index()
        {
            return View();
        }
    }
}

ColorVRWebSite/ColorVRWebSite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ColorVRWebSite.Data.Interfaces;
using ColorVRWebSite.ViewModels;

namespace ColorVRWebSite.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPlayGroundRepository _playGroundRepository;
        public HomeController(IPlayGroundRepository playGroundRepository)
        {
            _playGroundRepository = playGroundRepository;
        }
        public ViewResult Index()
        {
            var homeViewModel = new HomeViewModel
            {
                preferedPlayGrounds = _playGroundRepository.PreferredPlayGrounds
            };
            return View(homeViewModel);
        }
    }
}

ColorVRWebSite/ColorVRWebSite/Controllers/PlayGroundsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ColorVRWebSite.Data.Interfaces;
using ColorVRWebSite.ViewModels;
using ColorVRWebSite.Data.Models;

namespace ColorVRWebSite.Controllers
{
    public class PlayGroundsController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IPlayGroundRepository _playGroundRepository;
        public PlayGroundsController(ICategoryRepository categoryRepository, IPlayGroundRepository playGroundRepository)
        {
            _categoryRepository = categoryRepository;
            _playGroundRepository = playGroundRepository;
        }

        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<PlayGrounds> playGrounds;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(category))
            {
                playGrounds = _playGroundRepository.playGrounds.OrderBy(n => n.PGId);
                currentCategory = "All PlayGrounds";
            }
            else
            {
                if (string.Equals("Physics", _category, StringComparison.OrdinalIgnoreCase))
                {
                    playGrounds = _playGroundRepository.playGrounds.Where(p=>p.category.CategoryName.Equals("Physics")).OrderBy(p => p.Name);
                }
                else
                    playGrounds = _playGroundRepository.playGrounds.Where(p => p.category.CategoryName.Equals("Chemestry")).OrderBy(p => p.Name);
                
                currentCategory = _category;
            }

            return View(new PlayGroundsListViewModel
            {
                playGrounds = playGrounds,
                currentCategory = currentCategory
            });
        }
        public ViewResult Search(string searchString)
        {
            string _searchString = searchString;
            IEnumerable<PlayGrounds> playGrounds;
            string currentCategory = string.Empty;

            if (string.IsNullOrEmpty(_searchString))
            {
                playGrounds = _playGroundRepository.playGrounds.OrderBy(p => p.PGId);
            }
            else
            {
                playGrounds = _playGroundRepository.playGrounds.Where(p => p.Name.ToLower().Contains(_searchString.ToLower()));
            }

            return View("~/Views/Drink/List.cshtml", new PlayGroundsListViewModel { playGrounds = playGrounds, currentCategory = "All drinks" });
        }
        public ViewResult Details(int drinkId)
        {
            var playGrounds = _playGroundRepository.playGrounds.FirstOrDefault(d => d.PGId == drinkId);
            if (playGrounds == null)
            {
                return View("~/Views/Error/Error.cshtml");
            }
            return View(playGrounds);
        }
    }
}

ColorVRWebSite/ColorVRWebSite/Views/Contact/Index.cshtml
<h1>Contact Us</h1>
<p>If you have any questions do not hessitate to contact us:</p>

<email Address="param.a.joshi@gmail.com" Content="Email us"></email>

ColorVRWebSite/ColorVRWebSite/Views/Home/Index.cshtml
@model HomeViewModel

<h3>A Complete Virtual Reality Learning Platform</h3>

@await Html.PartialAsync("Carousel")

<h2 class="center_div container">Prefered Playgrounds of the Week</h2>
<h4 class="center_div container">Clients preferences - just for you!</h4>

<div class="row">
    @foreach (var pg in Model.preferedPlayGrounds)
    {
        @Html.Partial("PlayGroundsSummary", pg)
    }
</div>

ColorVRWebSite/ColorVRWebSite/Views/PlayGrounds/List.cshtml
<div>
    <h2> All PlayGrounds are shown here</h2>
</div>
<h2>@Model.currentCategory</h2>
@{ 
    foreach(PlayGrounds pg in Model.playGrounds)
    {
        @Html.Partial("PlayGroundsSummary", pg)
    }
}

ColorVRWebSite/ColorVRWebSite/Views/Shared/Carousel.cshtml
<div class="row carousel-holder marginTop1">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="http://localhost:50493/images/SolarSystemThumbNail.jpg" alt="">
                </div>
                <div class="item">
                    <img class="slide-image" src="http://localhost:50493/images/PeriodicTableThumbNail.jpg" alt="">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

ColorVRWebSite/ColorVRWebSite/Views/Shared/Components/CategoryMenu/Default.cshtml
<li class="dropdown">
    <a asp-controller="PlayGrounds"
       asp-action="Index"
        data-toggle="dropdown">PlayGrounds<b class="caret"></b></a>
    <ul class="dropdown-menu">
        @foreach (var category in Model)
        {
            <li>
                <a asp-controller="PlayGrounds" asp-action="List"
                   asp-route-category="@category.CategoryName">@category.CategoryName</a>
            </li>
        }
        <li class="divider"></li>
        <li>
            <a asp-controller="PlayGrounds" asp-action="List" asp-route-category="">View all PlayGrounds</a>
        </li>
    </ul>
</li>

ColorVRWebSite/ColorVRWebSite/Views/Shared/LoginPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore

@inject SignInManager<IdentityUser> SignInManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" id="logoutForm"
          method="post" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a id="registerLink" asp-controller="Account" asp-action="Register"> Register </a></li>
        <li><a id="loginLink" asp-controller="Account" asp-action="Login"> Log in </a></li>
    </ul>
}

ColorVRWebSite/ColorVRWebSite/Views/Shared/PlayGroundsSummary.cshtml
@model PlayGrounds

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.ImageThumbnail" alt="" />
        <div class="caption">
            <h3><a>@Model.Name</a></h3>
            <p>@Model.ShortDescription</p>
        </div>
    </div>
</div>

ColorVRWebSite/ColorVRWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro">
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/site.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <title>@ViewBag.Title</title>

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }
    </style>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    @await Component.InvokeAsync("CategoryMenu")
                    <li><a asp-controller="About" asp-action="Index">About</a></li>
                </ul>
                @await Html.PartialAsync("LoginPartial")
                <form class="navbar-form navbar-right" asp-controller="PlayGrounds" asp-action="Search" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search for a drink" name="searchString" value="@ViewData["searchString"]">
                    </div>
                </form>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Color VR</p>
        </footer>
    </div>
</body>
</html>